"""Port for observing game events (UI updates, metrics collection)."""

from __future__ import annotations

from typing import Protocol

from tarok.entities.card import Card
from tarok.entities.game_state import Contract, GameState, Trick


class GameObserverPort(Protocol):
    """Notified about game events — implemented by WebSocket broadcaster, training metrics, etc."""

    async def on_game_start(self, state: GameState) -> None: ...
    async def on_deal(self, state: GameState) -> None: ...
    async def on_bid(self, player: int, bid: Contract | None, state: GameState) -> None: ...
    async def on_contract_won(self, player: int, contract: Contract, state: GameState) -> None: ...
    async def on_king_called(self, player: int, king: Card, state: GameState) -> None: ...
    async def on_talon_revealed(self, groups: list[list[Card]], state: GameState) -> None: ...
    async def on_talon_group_picked(self, state: GameState) -> None: ...
    async def on_talon_exchanged(self, state: GameState) -> None: ...
    async def on_trick_start(self, state: GameState) -> None: ...
    async def on_card_played(self, player: int, card: Card, state: GameState) -> None: ...
    async def on_rule_verified(self, player: int, rule: str, state: GameState) -> None: ...
    async def on_trick_won(self, trick: Trick, winner: int, state: GameState) -> None: ...
    async def on_game_end(self, scores: dict[int, int], state: GameState) -> None: ...
