from typing import Any

PHASE_BIDDING: int
PHASE_KING_CALLING: int
PHASE_TALON_EXCHANGE: int
PHASE_ANNOUNCEMENTS: int
PHASE_TRICK_PLAY: int
PHASE_SCORING: int
PHASE_FINISHED: int
DT_BID: int
DT_KING_CALL: int
DT_TALON_PICK: int
DT_CARD_PLAY: int

CONTRACT_KLOP: int
CONTRACT_THREE: int
CONTRACT_TWO: int
CONTRACT_ONE: int
CONTRACT_SOLO_THREE: int
CONTRACT_SOLO_TWO: int
CONTRACT_SOLO_ONE: int
CONTRACT_SOLO: int
CONTRACT_BERAC: int
CONTRACT_BARVNI_VALAT: int
CONTRACT_VALAT: int

VARIANT_FOUR_PLAYER: int
VARIANT_THREE_PLAYER: int

class RustGameState:
    dealer: int
    phase: int
    variant: int
    num_players: int
    contract: int | None
    declarer: int | None
    partner: int | None
    called_king: int | None
    current_player: int

    def __init__(self, dealer: int = 0, variant: int = 0) -> None: ...
    @staticmethod
    def card_label(card_idx: int) -> str: ...
    @staticmethod
    def card_points(card_idx: int) -> int: ...
    @staticmethod
    def card_beats(a: int, b: int, lead_suit: int | None) -> bool: ...
    @staticmethod
    def compute_card_points(card_indices: list[int]) -> int: ...
    def hand(self, player: int) -> list[int]: ...
    def talon(self) -> list[int]: ...
    def get_role(self, player: int) -> int: ...
    def legal_bids(self, player: int) -> list[int | None]: ...
    def legal_plays(self, player: int) -> list[int]: ...
    def legal_plays_mask(self, player: int) -> Any: ...
    def callable_kings(self) -> list[int]: ...
    def start_trick(self, lead_player: int) -> None: ...
    def play_card(self, player: int, card_idx: int) -> None: ...
    def finish_trick(self) -> tuple[int, int]: ...
    def build_talon_groups(self) -> list[list[int]]: ...
    def set_talon_revealed(self, groups: list[list[int]]) -> None: ...
    def apply_talon_pick(self, group_idx: int) -> None: ...
    def apply_discards(self, card_indices: list[int]) -> None: ...
    def apply_king_call(self, card_idx: int) -> None: ...
    def set_called_king(self, card_idx: int) -> None: ...
    def add_to_hand(self, player: int, card_idx: int) -> None: ...
    def remove_from_talon(self, card_idx: int) -> None: ...
    def remove_card(self, player: int, card_idx: int) -> None: ...
    def add_put_down(self, card_idx: int) -> None: ...
    def add_bid(self, player: int, contract: int | None) -> None: ...
    def resolve_bidding(self, winner: int | None, contract: int | None) -> None: ...
    def set_role(self, player: int, role: int) -> None: ...
    def encode_state(self, player: int, decision_type: int) -> Any: ...
    def encode_state_3p(self, player: int, decision_type: int) -> Any: ...
    def encode_oracle_state_3p(self, player: int, decision_type: int) -> Any: ...
    def score_game(self) -> list[int]: ...
    def score_game_breakdown_json(self) -> str: ...
    def deal(self) -> None: ...
    def deal_hands(self, hands: list[list[int]], talon: list[int]) -> None: ...

def run_self_play(*args: Any, **kwargs: Any) -> Any: ...
def compute_gae(*args: Any, **kwargs: Any) -> Any: ...
def generate_expert_data(*args: Any, **kwargs: Any) -> Any: ...
def generate_dd_training_data(*args: Any, **kwargs: Any) -> Any: ...
def pimc_choose_card(
    gs: RustGameState,
    viewer: int,
    num_worlds: int = 100,
    seed: int | None = None,
) -> int: ...
def pimc_berac_choose_card(
    gs: RustGameState,
    viewer: int,
    num_worlds: int = 2,
    seed: int = 0,
) -> int: ...
def pimc_berac_votes(
    gs: RustGameState,
    viewer: int,
    num_worlds: int = 2,
    seed: int = 0,
) -> list[tuple[int, int, int]]: ...
