"""Shared model package used by backend inference and training-lab."""

from tarok_model.encoding import (
    ANNOUNCE_ACTION_SIZE,
    ANNOUNCE_IDX_TO_ANN,
    ANNOUNCE_PASS,
    BID_ACTION_SIZE,
    BID_ACTIONS,
    BID_TO_IDX,
    CARD_ACTION_SIZE,
    CARD_TO_IDX,
    DecisionType,
    GameMode,
    KING_ACTION_SIZE,
    KING_ACTIONS,
    KONTRA_IDX_TO_KEY,
    SUIT_TO_IDX,
    TALON_ACTION_SIZE,
    card_idx_to_card,
    contract_to_game_mode,
    encode_announce_mask,
    encode_bid_mask,
    encode_king_mask,
    encode_legal_mask,
    encode_oracle_state,
    encode_state,
    encode_talon_mask,
)
from tarok_model.network import TarokNet, TarokNetV4, TarokNetV5
from tarok_model.compute import ComputeBackend, create_backend

__all__ = [
    "ANNOUNCE_ACTION_SIZE",
    "ANNOUNCE_IDX_TO_ANN",
    "ANNOUNCE_PASS",
    "BID_ACTION_SIZE",
    "BID_ACTIONS",
    "BID_TO_IDX",
    "CARD_ACTION_SIZE",
    "CARD_TO_IDX",
    "DecisionType",
    "GameMode",
    "KING_ACTION_SIZE",
    "KING_ACTIONS",
    "KONTRA_IDX_TO_KEY",
    "SUIT_TO_IDX",
    "TALON_ACTION_SIZE",
    "TarokNet",
    "TarokNetV4",
    "ComputeBackend",
    "card_idx_to_card",
    "contract_to_game_mode",
    "create_backend",
    "encode_announce_mask",
    "encode_bid_mask",
    "encode_king_mask",
    "encode_legal_mask",
    "encode_oracle_state",
    "encode_state",
    "encode_talon_mask",
]